microservice:
  fullnameOverride: "myservice-test"
  replicaCount: 2
  workloadType: deployment
  image:
    repository: 818600128395.dkr.ecr.ap-southeast-1.amazonaws.com/playstudio/myservice
    tag: "4079f0f364f1be18fd9c7f0061d5dddebadb3c56"
    digest: "sha256:66f2297144ca98c1434aab65710fff86018d19bcf1de6a1a5ecdca2359545609"
    pullPolicy: IfNotPresent
  imagePullSecrets:
  - name: ecr-secret
  resources:
    requests: {cpu: 50m, memory: 32Mi}
    limits: {memory: 64Mi}

  ingress:
    enabled: true
    host: myservice-test.local

  topologySpreadConstraints: []
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - myservice
          topologyKey: "kubernetes.io/hostname"

  autoscaling: # chỉ có hiệu lực khi workloadType=deployment
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  # replicaCount=1 (default) + minAvailable=1 (default) would block all voluntary eviction/node drain.
  podDisruptionBudget:
    minAvailable: 1
    #maxUnavailable: 1
