microservice:
  fullnameOverride: "myservice-prod"
  #replicaCount: 4
  workloadType: deployment
  image:
    repository: 818600128395.dkr.ecr.ap-southeast-1.amazonaws.com/playstudio/myservice
    tag: "6158c7e084ea43669707941f2873c0ecd1d9ead2"
    digest: "sha256:66f2297144ca98c1434aab65710fff86018d19bcf1de6a1a5ecdca2359545609"
    pullPolicy: IfNotPresent
  imagePullSecrets:
  - name: ecr-secret
  resources:
    requests: {cpu: 200m, memory: 400Mi}
    limits: {memory: 800Mi}

  ingress:
    enabled: true
    host: myservice-prod.local

  topologySpreadConstraints: []
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - myservice
        topologyKey: "kubernetes.io/hostname"

  autoscaling: # chỉ có hiệu lực khi workloadType=deployment
    enabled: true
    minReplicas: 4
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  # replicaCount=1 (default) + minAvailable=1 (default) would block all voluntary eviction/node drain.
  podDisruptionBudget:
    minAvailable:
    maxUnavailable: 2
