microservice:
  fullnameOverride: "myservice-qa"
  replicaCount: 4
  workloadType: deployment
  image:
    repository: rockman88v/playstudios-myservice
    tag: "v1.0.0"
    pullPolicy: IfNotPresent

  resources:
    requests: { cpu: 100m, memory: 200Mi }
    limits: { memory: 500Mi } 

  ingress:
    enabled: true
    host: myservice-qa.local

  topologySpreadConstraints: []
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - myservice
        topologyKey: "kubernetes.io/hostname"

  autoscaling: # chỉ có hiệu lực khi workloadType=deployment
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  # replicaCount=1 (default) + minAvailable=1 (default) would block all voluntary eviction/node drain.
  podDisruptionBudget:
    minAvailable: 2
    #maxUnavailable: 1
